import 'dotenv/config'
import fs from 'fs'
import path from 'path'
import pg from 'pg'
import { fileURLToPath } from 'url'
import logger from '../utils/logger.js'
import crypto from 'crypto'

const { Client } = pg

// Recreate __dirname in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ∨∨∨ The following env variables are required!!! ∨∨∨
const envPath = path.join(__dirname, '..', '.env');

if (process.env?.NODE_ENV !== 'production' && !fs.existsSync(envPath)) {
    const autoGeneratedSecret = crypto.randomBytes(64).toString('hex');
    const defaultEnv = [
        `PORT=3001`,
        `DB_USER=postgres`,
        `DB_PASSWORD=`,
        `DB_HOST=localhost`,
        `DB_PORT=5432`,
        `DB_NAME=rdiploma`,
        `GOOGLE_CLIENT_ID=`,
        `GOOGLE_CLIENT_SECRET=`,
        `SESSION_SECRET=${autoGeneratedSecret}`
    ]
        .filter(Boolean)
        .join('\n');

    fs.writeFileSync(envPath, defaultEnv);
    logger.info(`Created missing .env file at: ${envPath}`);
    logger.info(`Please fill in the empty values! And modify any default values if necessary!`);
}

let PORT

try {
    PORT = process.env.PORT
    const DB_PASSWORD = process.env.DB_PASSWORD
    const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID
    const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET
    const SESSION_SECRET = process.env.SESSION_SECRET

    const envVariables = {
        PORT: PORT,
        DB_PASSWORD: DB_PASSWORD,
        GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
        GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET,
        SESSION_SECRET: SESSION_SECRET
    }

    const entries = Object.entries(envVariables)
    const values = Object.values(envVariables)

    if (values.includes(undefined) || values.includes('')) {
        //logger.info(`Env variables expected: ${Object.keys(envVariables)}\n`)
        //logger.info(`Env variables found: ${entries.map(e => !e[1] ? '-undefined-' : e[0])}\n`)
        logger.error(`Missing env variables required in ${process.env.NODE_ENV} environment`)
        throw new Error(`>>> Missing env variables:${entries.reduce((res, e) => {
            if (!e[1]) {
                res.push(` ${e[0]}`)
            }
            return res
        }, [])
            }\n`)
    }
} catch (err) {
    logger.info(err)
    logger.info(`To solve this, create a file with the name .env to backend/ and add the required variables to it, variables can be found in GitHub at https://github.com/Osoito/ReadingDiplomaWebGame_Capstone1?tab=readme-ov-file#backend`)
    process.exit(1)
}

// ∧∧∧ These env variables are required!!! ∧∧∧

// Automatically creates the rdiploma database and a db/migrations folder needed for the knex migrations

async function createDatabase() {
    const client = new Client({
        user: process.env.DB_USER || 'postgres',
        password: process.env.DB_PASSWORD,
        host: process.env.DB_HOST || 'localhost',
        port: process.env.DB_PORT || 5432,
        database: 'postgres'
    })

    await client.connect()
    const dbName = process.env.DB_NAME || 'rdiploma'

    const result = await client.query(
        `SELECT 1 FROM pg_database WHERE datname = $1`,
        [dbName]
    )

    if (result.rowCount === 0) {
        logger.info(`Database "${dbName}" does not exist. Creating...`)
        await client.query(`CREATE DATABASE ${dbName}`)
        logger.info(`Database "${dbName}" created.`)
    } else {
        logger.info(`Database "${dbName}" already exists.`)
    }

    // ensure db/migrations folder exists
    const migrationsDir = path.join(__dirname, '..', 'db', 'migrations');

    if (!fs.existsSync(migrationsDir)) {
        fs.mkdirSync(migrationsDir, { recursive: true });
        logger.info(`Migrations folder was missing. Created folder at '../db/migrations': ${migrationsDir}`);
    }

    // ensure public/uploads/book-covers folder exists
    const bookCoversDir = path.join(__dirname, '..', 'public', 'uploads', 'book-covers')

    if (!fs.existsSync(bookCoversDir)) {
        fs.mkdirSync(bookCoversDir, { recursive: true });
        logger.info(`Book covers folder was missing. Created folder at '../public/uploads/book-covers': ${bookCoversDir}`);
    }
    await client.end()
}

await createDatabase().catch((err) => {
    logger.error(err)
    process.exit(1)
})